---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - hiring.influxdata.io
  resources:
  - emailrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hiring.influxdata.io
  resources:
  - emailrequests/finalizers
  verbs:
  - update
- apiGroups:
  - hiring.influxdata.io
  resources:
  - emailrequests/status
  verbs:
  - get
  - patch
  - update
